name: FamiliaEscolaApp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  firebase_analytics: ^12.0.1
  provider: ^6.1.5
  flutter_speed_dial: ^7.0.0
  intl: ^0.20.0
  fl_chart: ^0.63.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0 # versão mais recente
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/splash_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icone.png" # aqui você coloca a logo do app
  adaptive_icon_background: "#FFFFFF" # cor de fundo (Android)
  adaptive_icon_foreground: "assets/icone.png"