// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsSiljc4H3-IWGQPwlcdKHY2vE9uR7h0g',
    appId: '1:937377525670:web:4f0bd49983ac10f018e967',
    messagingSenderId: '937377525670',
    projectId: 'familia-e-escola',
    authDomain: 'familia-e-escola.firebaseapp.com',
    storageBucket: 'familia-e-escola.firebasestorage.app',
    measurementId: 'G-G11F0GP2VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz1vtf5JmbcRl2-AHzj6uk07g6smH9zuI',
    appId: '1:937377525670:android:39844ff0cb7f11eb18e967',
    messagingSenderId: '937377525670',
    projectId: 'familia-e-escola',
    storageBucket: 'familia-e-escola.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKg1_FJBORmu-x6zenMz3gsEgehmhp-_4',
    appId: '1:937377525670:ios:888178280077781e18e967',
    messagingSenderId: '937377525670',
    projectId: 'familia-e-escola',
    storageBucket: 'familia-e-escola.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKg1_FJBORmu-x6zenMz3gsEgehmhp-_4',
    appId: '1:937377525670:ios:888178280077781e18e967',
    messagingSenderId: '937377525670',
    projectId: 'familia-e-escola',
    storageBucket: 'familia-e-escola.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsSiljc4H3-IWGQPwlcdKHY2vE9uR7h0g',
    appId: '1:937377525670:web:ec2d87f15a1fde7518e967',
    messagingSenderId: '937377525670',
    projectId: 'familia-e-escola',
    authDomain: 'familia-e-escola.firebaseapp.com',
    storageBucket: 'familia-e-escola.firebasestorage.app',
    measurementId: 'G-SLP8E9NWJ9',
  );
}
